
version: '3'
services:
  jenkins:
    container_name: jenkins
    image: "jenkins:latest"
    ports:
      - "8090:8080"
  nexus:
    container_name: nexus
    image: "sonatype/nexus:latest"
    ports:
      - "8091:8081"
  sonar:
    container_name: sonar
    image: "sonarqube:latest"
    ports:
      - "9000:9000"
    depends_on:
      - "db"
    environment:
      SONARQUBE_JDBC_USERNAME: "sonar"
      SONARQUBE_JDBC_PASSWORD: "sonar"
      SONARQUBE_JDBC_URL: "jdbc:mysql://sonar-mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true"
   
  db:
    container_name: sonar-mysql
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "sonar"
      MYSQL_DATABASE: "sonar"
      MYSQL_USER: "sonar"
      MYSQL_PASSWORD: "sonar"

  nginx:
    container_name: nginx
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html